### ISSUE TITLE
Add 'binding' as a possible deviation cause to known-issues

### ISSUE THREAD

**Issue by jduwel** [Nictiz/Nictiz-R4-zib2020#299]
https://github.com/Nictiz/Nictiz-R4-zib2020/commit/d3315dfdb21eb2c040e7b7f7a4ec88c23f65bd32

Had to remove this to 'make it work', but it seems like a valid deviation cause that should be added?

**Comment by pieter-edelman-nictiz** [comment]
I'm not sure I can't really parse this ticket anymore. @jduwel , do you still know what this is about?

**Comment by jduwel** [comment]
When it comes to the date, this is around the time of the release of Lab 3.0: https://informatiestandaarden.nictiz.nl/index.php?title=Lab:V3.0.0_FHIR_Lab2zorg&action=history

I do see that https://zibs.nl/wiki/LaboratoryTestResult-v4.6(2020EN)#ContainerTypeCodelist has a required binding and that the binding in the profile https://simplifier.net/packages/nictiz.fhir.nl.r4.zib2020/0.9.0-beta.1/files/2004489 is extensible.
In https://simplifier.net/packages/nictiz.fhir.nl.r4.nl-core/0.9.0-beta.1/files/2004675 a new binding is added with a comment on it.

I guess someone was trying to add this to known-issues aswell and did in a way that was not valid following our QA. So I had to remove it before I probably could approve/merge some PR.

The underlying issue that this whole move is not following our guidelines, well I am aware. Perhaps we should focus on 'knitting that straight' in some way. But I am not sure what the status of LabTestResult as a whole is.

**Comment by pieter-edelman-nictiz** [comment]
But the QA tooling doesn't check binding strength, does it? So there's not really an exception to document.

If you _want_ to document this exception anyway you can do so by picking a key that's not recognized by the tooling, in case it will be ignored. For example:
```yaml
zib-LaboratoryTestResult.Specimen:
  zib deviations:
    Specimen.identifier:
      - cardinality: 0..* instead of 0..1
        reason: Although a single SpecimenId is allowed according to the zib, .identifier is often used for additional identifiers outside the scope of the zib. It's not possible to create a slice or pattern specifically for SpecimenId without further formal requirements by the zib.
  notes:
    Specimen.container.type:
      - note: The binding strength is set to extensible instead of required, because ...
```
